name: Setup Terraform
description: Install and configure Terraform with caching

inputs:
  terraform-version:
    description: Terraform version to install
    required: true
    default: '1.7.5'
  working-directory:
    description: Working directory for Terraform
    required: false
    default: terraform
  cache-terraform:
    description: Enable Terraform cache
    required: false
    default: 'true'

outputs:
  terraform-version:
    description: Installed Terraform version
    value: ${{ steps.setup.outputs.terraform_version }}

runs:
  using: composite
  steps:
    - name: Setup Terraform
      id: setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Cache Terraform plugins
      if: inputs.cache-terraform == 'true'
      uses: actions/cache@v4
      with:
        path: |
          ~/.terraform.d/plugin-cache
          ${{ inputs.working-directory }}/.terraform
        key: terraform-${{ inputs.terraform-version }}-${{ hashFiles(format('{0}/.terraform.lock.hcl', inputs.working-directory)) }}
        restore-keys: |
          terraform-${{ inputs.terraform-version }}-

    - name: Initialize Terraform plugin cache
      if: inputs.cache-terraform == 'true'
      shell: bash
      run: mkdir -p ~/.terraform.d/plugin-cache
      env:
        TF_PLUGIN_CACHE_DIR: ~/.terraform.d/plugin-cache

    - name: Verify Terraform installation
      shell: bash
      run: terraform -version
